### ISSUE TITLE
Read/Write only by Sectors

### ISSUE THREAD

**Issue by juancols** [4ZM/mfterm#33]
Hello everyone,

I'm using a MIFARE Classic 1k with damaged Sectors from 07 to 15. However, I want to read/write my data only in Sector 02. The problem is that the commands read/write are executed in the whole tag, given me errors similar to:

`Unable to read block: 0x1e. Read failed!`

Is it possible to Read/Write only by Sectors? Does anyone know an alternative way to do it?

Thanks!

**Comment by 4ZM** [comment]
Hi!

You could try to replace the "return false;" at line 397 in mifare_ctrl.c with a "continue;" and recompile.

Let me know if it works.

**Comment by juancols** [comment]
Dear @4ZM ,

Thanks for the suggestion. I tried it and this was the result:

1) I created a dictionary with a list of keys that I previously found using [mfoc](http://tools.kali.org/wireless-attacks/mfoc).

2) I loaded the keys to the dictionary and then I performed a dict attack. All the A-keys were found (the B-keys from sectors: 0, 1, 6 and 7 couldn't be found). 

3) I tested the keys authentication. (Note: I've modified the keys original values from the text below)

$keys test 1k A
xS  T  Key           Status
----------------------------
00  a  000000000000   Success
01  a  000000000000   Success
02  a  000000000000   Success
03  a  000000000000   Success
04  a  000000000000   Success
05  a  000000000000   Success
06  a  000000000000   Success
07  a  000000000000   Success
08  a  000000000000  Success
09  a  000000000000  Success
0a  a  000000000000  Success
0b  a  000000000000  Success
0c  a  000000000000  Success
0d  a  000000000000  Success
0e  a  000000000000  Success
0f  a  000000000000  Success

4) I tried to read the card and this is what I got:

$read a
Reading: [.........
Unable to read block: 0x1e.

Unable to read block: 0x1d.

Unable to read block: 0x1c.
0x06..
Unable to read block: 0x16.

Unable to read block: 0x15.

Unable to read block: 0x14.
0x04..
Unable to read block: 0x0e.

Unable to read block: 0x0d.

Unable to read block: 0x0c.
0x02...] Auth errors in indicated sectors.
Read MIFARE Classic 1k (SAK: 08, ATQA: 00 04)

5) The problem is that even if the reading process keeps going despite not being able to read some blocks, I'm getting only blank data from Sectors 02 to 15: (from the output below I only modified the lines where the keys were located. Sectors 0 and 1 are omitted but correct in the original output)

$ print
xS  xB                                                                                      ASCII       
------------------------------------------------------------------------------------------

02  08  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
02  09  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
02  0a  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
02  0b  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

03  0c  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
03  0d  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
03  0e  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
03  0f   X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

04  10  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
04  11  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
04  12  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
04  13  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

05  14  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
05  15  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
05  16  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
05  17  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

06  18  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
06  19  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
06  1a  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
06  1b  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

07  1c  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
07  1d  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
07  1e  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
07  1f  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

08  20  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
08  21  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
08  22  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
08  23  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

09  24  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
09  25  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
09  26  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
09  27  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

0a  28  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0a  29  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0a  2a  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0a  2b  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

0b  2c  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0b  2d  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0b  2e  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0b  2f  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

0c  30  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0c  31  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0c  32  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0c  33  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

0d  34  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0d  35  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0d  36  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0d  37  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

0e  38  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0e  39  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0e  3a  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0e  3b  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

0f  3c  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0f  3d  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0f  3e  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  [................]
0f  3f  X   X   X   X   X   X   X   X   X   X   X   X   X   X   X  X [................]

I checked with [MIFARE Classic Tool](http://www.proxmark.org/forum/viewtopic.php?id=1535) that sectors 02 and 03 actually have data. What could be wrong around here? It would be really helpful if there was a couple of commands for reading and writing single sectors!

Thanks in advance for your help.

**Comment by 4ZM** [comment]
Hm, not sure what is going on here. There are two things that seem wrong.

1. From the output (with Unable... removed): [.........0x06..0x04..0x02...] Auth errors in indicated sectors.
This implies that libnfc could authenticate with the tag in all sectors except 6, 4 & 2. So it's wierd that the key test command reports success for these sectors. 

2. It seems that there are problems reading even some blocks in sectors that have been successfully authenticated. My previous suggestion should lead to those blocks being ignored (and the blocks being filled with random - probably 0 data). All other blocks in sectors where the auth was successfull should be unaffected by this and get populated.

Are the results you are seeing consistent on multiple reads and keytests? What kind of reader device do you have and can you try positioning the tag slightly different in relation to the reader. If the tag has a damaged antenna, it might cause wierd stuff like this due to weak signal/poor power transfer. That might explain why MIFAre Classic Tool worked, it uses a different reader (phone) right?

**Comment by juancols** [comment]
Hello @4ZM 

I just wanted to let you know that I haven't continued with the tests for now, but I thank you for all your help and great job!

The reader I'm using is the [Adafruit PN532 NFC/RFID breakout board](https://www.adafruit.com/product/364) connected to my PC through a [FTDI USB/Serial converter](https://www.sparkfun.com/products/11812). 

And exactly! I installed the MIFARE Classic Tool in a Samsung Galaxy S3. Everything worked fine.

I'll let you know any other finding if I continue with the tests. 

Thanks again.

**Comment by 4ZM** [comment]
Ait! Closing this issue. Open a new one if you get any more info
