### ISSUE TITLE
Compilation failed with recent gcc

### ISSUE THREAD

**Issue by yapbreak** [4ZM/mfterm#36]
With recent gcc (mine is 8.2.1), I get the following error when compiling on Linux:
```
gcc -DHAVE_CONFIG_H -I.   -D_FORTIFY_SOURCE=2 -g -Wall -Wconversion -std=c99 -Werror -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -MT tag.o -MD -MP -MF .deps/tag.Tpo -c -o tag.o tag.c
tag.c: In function ‘print_tag_byte_bits’:
tag.c:132:10: error: ‘<<’ in boolean context, did you mean ‘<’ ? [-Werror=int-in-bool-context]
     if (1<<i && data)
         ~^~~
cc1: all warnings being treated as errors
```

Should it be the following line instead?
```
if ((1<<i) & data)
```

I compile mfterm using an up-to-date archlinux, through AUR package mfterm-git.

Regards.

**Comment by 4ZM** [comment]
A bugfix is now on master https://github.com/4ZM/mfterm/commit/e13d373cc23c4e0b89f112b5e4e6d21f737d937e
